### ISSUE TITLE
Invite endpoint fails with 500 when redirect_uri is invalid

### ISSUE THREAD

**Issue by spruce-bruce** [synapsestudios/oidc-platform#109]
### Steps to Reproduce
1. Create a client with redirect url like "http://hello.com/whatever". 
2. Attempt to invite a user to that client using redirect "http://noway.com/not-whatever".

### Log output
```
170719/173324.749, [error] message: Cannot provide statusCode or message with boom error, stack: Error: Cannot provide statusCode or message with boom error
    at Object.exports.assert (/src/node_modules/boom/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.wrap (/src/node_modules/boom/lib/index.js:76:10)
    at Object.internals.serverError (/src/node_modules/boom/lib/index.js:393:25)
    at Object.exports.badImplementation (/src/node_modules/boom/lib/index.js:430:27)
    at Child.clientService.findByRedirectUriAndClientId.then.then.then.then.catch.error (/src/src/application/user/user-service.js:102:54)
    at bound (domain.js:301:14)
    at Child.runBound (domain.js:314:12)
    at runCallback (timers.js:800:20)
From previous event:
    at Object.inviteUser (/src/src/application/user/user-service.js:102:39)
    at handler (/src/src/application/api/api-routes.js:10:25)
    at Object.internals.handler (/src/node_modules/hapi/lib/handler.js:101:51)
    at request._protect.run (/src/node_modules/hapi/lib/handler.js:32:23)
    at module.exports.internals.Protect.internals.Protect.run (/src/node_modules/hapi/lib/protect.js:59:12)
    at exports.execute (/src/node_modules/hapi/lib/handler.js:26:22)
    at each (/src/node_modules/hapi/lib/request.js:404:16)
    at iterate (/src/node_modules/items/lib/index.js:36:13)
    at done (/src/node_modules/items/lib/index.js:28:25)
    at postValidate (/src/node_modules/hapi/lib/validation.js:68:20)
    at Hoek.once (/src/node_modules/hapi/lib/protect.js:49:16)
    at wrapped (/src/node_modules/hapi/node_modules/hoek/lib/index.js:871:20)
    at Promise.all.then (/src/src/lib/validator/mixed-validation.js:47:13)
    at <anonymous>
170719/173324.749, [response] http://61ce4b1487bb:9000: post /api/invite {} 500 (36ms)
```

**Comment by spruce-bruce** [comment]
Need to try and repro this. Probably not a problem anymore

**Comment by spruce-bruce** [comment]
Solved on another issue, this returns a 403 forbidden now.
