### ISSUE TITLE
Uploading photo to '/user/profile' route breaks in profileHandler

### ISSUE THREAD

**Issue by zacharyweidenbach** [synapsestudios/oidc-platform#235]
Get a 500 error from server, and error in teminal:
```
oidc_1           | error: 171129/235545.074, [error] message: uuid is not defined, stack: ReferenceError: uuid is not defined
oidc_1           |     at profileHandler.formHandler (/src/src/application/user/user-controller.js:104:22)
oidc_1           |     at /src/src/lib/form-handler.js:29:23
oidc_1           |     at <anonymous>
oidc_1           | info: 171129/235545.074, [response] http://e51ca19c587f:9000: post /user/profile {"client_id":"client_id","redirect_uri":"https://localhost.dev:3000/post-login"} 500 (24ms)
``` 
logged into container and checked node_modules and confirmed uuid package is installed. File type was jpeg, 500X500px, 98KB.

**Comment by liruenth** [comment]
Blocked by helia 861
