### ISSUE TITLE
Npm run rebuild-db fails

### ISSUE THREAD

**Issue by pcavagna** [synapsestudios/oidc-platform#55]
## DESCRIPTION
Npm run rebuild-db fails

## CONSOLE ERROR
Using MySQL:  
```
/src/src/bin/drop-tables.js:10
.raw('DROP SCHEMA public CASCADE')
^

TypeError: Cannot read property 'raw' of undefined
at Object.<anonymous> (/src/src/bin/drop-tables.js:10:5)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3
```

## Solution
Remove this script

**Comment by bobeagan** [comment]
Need to figure out if we should just remove this script or spend the time to have a more DB-agnostic way to handle this.
